name: SonarQube
on:
  workflow_run:
    workflows: [ "Tests" ]
    types:
      - completed
jobs:
  prdetails:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'
    uses: t3chguy/matrix-js-sdk/.github/workflows/pr_details.yml@develop
    with:
      owner: ${{ github.event.workflow_run.head_repository.owner.login }}
      branch: ${{ github.event.workflow_run.head_branch }}

  sonarqube:
    needs: prdetails
    if: github.event.workflow_run.conclusion == 'success'
    uses: t3chguy/matrix-js-sdk/.github/workflows/sonarcloud.yml@develop
    with:
      repo: ${{ github.event.workflow_run.head_repository.full_name }}
      pr_id: ${{ needs.prdetails.output.prnumber }}
      head_branch: ${{ needs.prdetails.outputs.headref || github.event.workflow_run.head_branch }}
      base_branch: ${{ needs.prdetails.outputs.baseref }}
      revision: ${{ github.event.workflow_run.head_sha }}
      coverage_workflow_name: tests.yml
      coverage_run_id: ${{ github.event.workflow_run.id }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
