name: SonarQube
on:
  workflow_run:
    workflows: [ "Tests" ]
    types:
      - completed
jobs:
  sonarqube:
    if: github.event.workflow_run.conclusion == 'success'
    uses: matrix-org/matrix-js-sdk/.github/workflows/sonarcloud.yml@develop
    with:
      is_pr: ${{ github.event.workflow_run.event == 'pull_request' }}
      repo: ${{ github.event.workflow_run.head_repository.full_name }}
      owner: ${{ github.event.workflow_run.head_repository.owner.login }}
      head_branch: ${{ github.event.workflow_run.head_branch }}
      revision: ${{ github.event.workflow_run.head_sha }}
      coverage_workflow_name: tests.yml
      coverage_run_id: ${{ github.event.workflow_run.id }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
