name: Tests
on:
  pull_request: { }
  push:
    branches: [ develop, main, master ]
jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
